compass_sdk/utils.py

When using process_folder in sdk, it seems to be stuck on a single file
* [imap function is being used for processing](https://github.com/cohere-ai/cohere-compass-sdk/blob/main/compass_sdk/parser.py#L150-L156)
* [definition of  imap_queue](https://github.com/cohere-ai/cohere-compass-sdk/blob/main/compass_sdk/parser.py#L150-L156)
* The interesting part is the [popleft line](https://github.com/cohere-ai/cohere-compass-sdk/blob/main/compass_sdk/utils.py#L24) , if one file is too big it will get stuck on that file and not process any further files.
That is why the processing is really slow if we have couple of big pdfs
This code aims to improve that by using `as_completed` and waits for only any first completed future
This PR introduces changes to the `compass_sdk/utils.py` and …

Fixing blocking behavior of imap_queued

---

compass_sdk/__init__.py
compass_sdk/compass.py
compass_sdk/rbac.py
compass_sdk/types.py

This PR introduces a new file, `compass_sdk/root_rbac.py`, which defines a `CompassRootClient` class for managing users, groups, and roles in a Compass system. The class provides methods for fetching, creating, and deleting users, groups, and roles, as well as managing role mappings.
The `CompassRootClient` class is initialised with a `compass_url` and a `root_user_token`, which are used to construct the base URL and authorisation headers for API requests. The class methods use the `requests` library to interact with the Compass API, performing various operations:
- `fetch_users` retrieves a list of users and returns a list of `UserFetchResponse` objects.
- `create_users` creates new users and returns a list of `UserCreateResponse` objects.
- `delete_users` deletes users by their names …

Adding rbac sdk path

---

compass_sdk/types.py

This PR removes the `ADMIN` permission from the `Permission` enum in the `compass_sdk/types.py` file.
- The `ADMIN` permission is no longer available in the `Permission` enum.

Removing admin from permissions

---

compass_sdk/__init__.py

This PR introduces a new `FilterType` called `WORD_MATCH` to the `compass_sdk/__init__.py` file.
- The `WORD_MATCH` filter type is added to the `FilterType` class.
- This new filter type is represented by the string `"$wordMatch"`.

Adds $match capability in Compass (via WORD_MATCH)

---

compass_sdk/parser.py

The PR introduces changes to the `process_file` function in `compass_sdk/parser.py`, specifically the way it handles document processing and metadata retrieval.
- The `docs` list is now initialised as an empty list.
- The loop iterates over `res.json()["docs"]` instead of `docs`.
- A new condition checks for the absence of errors in each document before processing.
- The `CompassDocument` instance is created and assigned to `compass_doc` instead of directly appending to `docs`.
- The `additional_metadata` is retrieved and added to the `compass_doc.content` dictionary.
- The `compass_doc` is then appended to the `docs` list.

Fix empty iterator due to wrong filtering expression

---

.github/workflows/test.yml
compass_sdk/__init__.py
pyproject.toml

This pull request introduces changes to the `compass_sdk/__init__.py` file, focusing on the configuration of the `ParserConfig` class and the parsing strategy.
The PR enhances the `ParserConfig class by adding a new `PDFParsingStrategy` enumeration, which defines parsing strategies for PDF documents. The `PDFParsingStrategy` enum includes two strategies: `QuickText` and `ImageToMarkdown`. The default strategy is set to `QuickText`.
Additionally, the `ParserConfig class is updated to inherit from `BaseModel` instead of `ValidatedModel`. This change allows for more flexible configuration options, as indicated by the `model_config` attribute, which enables arbitrary types and ignores extra fields.
- The `StrEnum` class is imported from the `enum` module.
- A new `PDFParsingStrategy` …

Remove apply_pdf_rough_text_extraction and add pdf_parsing_strategy

---

compass_sdk/__init__.py

This PR introduces a new class, `PresentationParsingStrategy`, which extends the `StrEnum` class. This class provides two parsing strategies for presentations: `Unstructured` and `ImageToMarkdown`. The `Unstructured` strategy is set as the default.
The `ParserConfig` class is also updated to include a new parameter, `presentation_parsing_strategy`, which is set to the `Unstructured` strategy by default.
- Added the `PresentationParsingStrategy` class.
- Added the `presentation_parsing_strategy` parameter to the `ParserConfig` class.

Add parameters for the new pptx parser

---

compass_sdk/__init__.py
compass_sdk/compass.py
pyproject.toml

Also, fix default values in pydantic models
**WHY**
When running `insert_docs`, errors in any document would be appended to a list of `errors` as a new dict `{doc_id: error}`. Hence the format of `errors` is expected to be a `List[Dict[str, str]]`. However, when calling `_get_request_blocks`, accumulated errors in older documents were appended to `errors` like this
```
if doc.status != CompassDocumentStatus.Success:
logger.error(f"[Thread {threading.get_native_id()}] Document #{num_doc} has errors: {doc.errors}")
errors.append(doc)
```
This means that `errors` may end up containing either `Dict[str, str]` or `CompassDocument`. Downstream, in North, they were expecting the first, and hence they would do something like `error.keys() for error in errors`, leading to an error like …

Fix bug when adding errors in insert_docs. 

---

compass_sdk/types.py
pyproject.toml

This pull request removes the `ROOT` permission from the `Permission` enum in the `compass_sdk/types.py` file.
- The `ROOT` permission is no longer available in the `Permission` enum.

Removing root from permissions. As root user cannot be created from here

---

compass_sdk/__init__.py
compass_sdk/compass.py
pyproject.toml

Certain document types (i.e., PDF and Slides) have available two parser versions:
Quick, or "lighter" parsing: processes the documents very fast, e.g., with pypdfium2 in the case of PDF, at the cost of semantic elements of the document being lost (e.g., tables and images).
"Heavy parsers", which use MiniCPM to extract the document text in Markdown format.
The default strategy for when to use heavy parsing has been, so far, to trigger it only when quick parsing fails. We call this approach the Fallback heavy parsing strategy.
In this PR, we add an alternative strategy to define when to use heavy parsing:
Complementary: runs heavy parsing after quick parsing, and replaces the document once it is done. This allows the document to be available in the index for retrieval in very short time, …

Configurable heavy parsing strategy

---

compass_sdk/compass.py

This PR introduces a new class, `SessionWithDefaultTimeout`, which extends the `requests.Session` class. This class is designed to handle HTTP requests with a default timeout value.
The `CompassClient` class has been updated to use the new `SessionWithDefaultTimeout` class for its `self.session` attribute, ensuring that all requests made by the client have a default timeout.
- A new class, `SessionWithDefaultTimeout`, is added, which inherits from `requests.Session`.
- The `CompassClient` class now initializes `self.session` with the `SessionWithDefaultTimeout` class, passing the default timeout value as an argument.

feat: add default timeout

---

compass_sdk/compass.py
compass_sdk/models/__init__.py
compass_sdk/models/search.py
pyproject.toml

Search APIs didn't have models and they were directly returning the generic response from the `_send_request` method.

Add models for search APIs

---

compass_sdk/compass.py
compass_sdk/exceptions.py
pyproject.toml

We were unnecessarily retrying on all 400 errors except 401. This change should fix the issue.

[SEA-1683] Fix retry mechanism for 400 errors

---

cohere/compass/clients/compass.py

This pull request introduces changes to the `__init__` method of the `compass.py` module, which is responsible for initializing a compass client to interact with the Compass API. The modifications primarily involve updating the handling of the `default_timeout` and introducing a new `http_session` parameter.
- The `default_timeout` parameter's type hint has been updated from `int` to `int | None`, indicating that it can now accept `None` as a valid value.
- A new parameter, `http_session`, has been added to the `__init__` method, allowing for the specification of an HTTP session with a custom timeout.
- The instantiation of the `SessionWithDefaultTimeout` class has been replaced with a conditional assignment, setting `self.session` to either the provided `http_session` or a new instance …

fix: Allows clients to pass in an HTTP Session

---

cohere/compass/clients/compass.py
cohere/compass/exceptions.py
pyproject.toml

Provide error code in CompassClientError to differentiate 400s

Propagate the 400 error codes

---

cohere/compass/models/datasources.py
pyproject.toml

This pull request updates the `DocumentStatus` class in the `datasources.py` file and the `version` in the `pyproject.toml` file.
- The `updated_at` field in the `DocumentStatus` class is now set to `None` by default.
- The `version` in the `pyproject.toml` file is updated from `0.10.0` to `0.10.1`.

fix: set the default value of DocumentStatus.updated_at to None.

---

cohere/compass/__init__.py
cohere/compass/clients/compass.py
cohere/compass/clients/parser.py
cohere/compass/clients/rbac.py
cohere/compass/constants.py
cohere/compass/exceptions.py
cohere/compass/models/__init__.py
cohere/compass/models/config.py
cohere/compass/models/datasources.py
cohere/compass/models/documents.py
cohere/compass/models/rbac.py
cohere/compass/models/search.py
cohere/compass/utils.py
pyproject.toml

To ensure high code quality and capture accidental issues at build time rather the run time, I am extending the Ruff rules enabled.

Introduce more Ruff rules to improve code quality

---

cohere/compass/__init__.py
cohere/compass/clients/compass.py
cohere/compass/exceptions.py
cohere/compass/models/documents.py
pyproject.toml
tests/test_compass_client.py

The main contribution of this PR is:
- The API used to return the RetryResult object. Now it returns a strong type.
- It used to be called `edit_group_authorization`. I renamed to `update_group_authorization` to match the API name.
While at this, I also changed the `_send_request` API to only accept objects of type BaseModel.  This is to reduce its complexity, and also the unify the way we are sending and receiving objects.

Add type support to update_group_authorization

---

cohere/compass/clients/parser.py
pyproject.toml

Setting a lower default value as we have only one cpu unit on the parser
User can increase it depending on the number of cpu cores or pod's

Reduce num_worker to 1

---

cohere/compass/clients/compass.py
cohere/compass/exceptions.py
tests/test_compass_client.py

We didn't handle connection aborted exception correctly. This change should fix it. 
Check this [sentry log](https://cohere-ai.sentry.io/issues/6152555962/?environment=north-prod&project=4508047123218432&query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D&sort=freq&statsPeriod=24h&stream_index=1)  for more details

handling connection aborted error

---

README.md

This pull request introduces changes to the `README.md` file, focusing on updating the configuration and usage of the Cohere Compass API.
- **API Configuration**: The `url` variable has been replaced with `api_url` and `parser_url`, providing a more structured approach to handling API endpoints.
- **Authentication**: A new variable, `bearer_token`, has been added to support authentication with the API. This token is passed to the `CompassClient` when creating the index.
- **Parsing Options**: The `process_folder` method now includes the `recursive` parameter, enabling recursive folder processing during parsing.
- **Search Results**: The search results retrieval has been modified to use the `result` variable, ensuring consistent access to the search outcomes.

Updating readme code

---

cohere/compass/clients/parser.py
cohere/compass/utils.py

Fixes 
```
ChunkedEncodingError: ('Connection broken: IncompleteRead(4632016 bytes read, 10217602 more expected)', IncompleteRead(4632016 bytes read, 10217602 more expected))
```
This issue was caused by a parser restarting or dying because of some reason. The request to parser failed and it was not handled gracefully. This change will retry the file X times (3 by default) and will fail gracefully with an error log if not able to parse the file
Adding multiple retries to process_file

Retry the file if parser fails

---

cohere/compass/clients/compass.py
cohere/compass/models/config.py
pyproject.toml
tests/test_compass_client.py

Adds the optional data body to the `create_index` call to allow the clients to configure number of shards or replicas.

Adding the ability to create an Index with an IndexConfig set

---

README.md

This PR introduces a new section on Role-Based Access Control (RBAC) in the README.md file, providing a code snippet for setting up user access control using the Cohere Compass API. The code demonstrates how to create users, add them to groups, create roles with specific permissions, and map roles to groups.
- Added a new section titled "RBAC" to the README.md file.
- Introduced Python code for user access control using the Cohere Compass API.
- Imported necessary modules from `cohere.compass.clients.rbac`, `cohere.compass.models.rbac`, and `requests.exceptions`.
- Defined variables for API configuration, user names, group name, role name, indexes, and permissions.
- Created users and added them to a group using the `CompassRootClient` instance.
- Created a role with specific permissions …

Updating readme with RBAC

---

cohere/compass/clients/access_control.py
cohere/compass/clients/rbac.py
cohere/compass/models/access_control.py
pyproject.toml

Implements the V2 api as `access_control` module allowing new versions of the SDK to interact with the V2 api.
Marks V1 as to be deprecated so that folks do not choose to use the V1 implementation in `rbac` module
Increment the version of the SDK.

feat: implement the V2 access control apis

---

.vscode/settings.json
cohere/compass/clients/compass.py
pyproject.toml

The `search_chunks` and `search_documents` APIs are not handling errors in responses, resulting in the error response from the APIs being parsed as a Pydantic model, which shows a confusing error to the clients. This should fix it.

Raise exception in case of errors in search APIs

---

cohere/compass/clients/compass.py
pyproject.toml

Some APIs, e.g. search APIs, were hard-coding the retry count and sleep time to 1 and 1, respectively. Others, used the DEFAULT_MAX_RETRIES and DEFAULT_SLEEP_RETRY_SECONDS constants, respectively. Yet others allowed passing values from the clients. This PR fixes this as follows:
1. Introduce `default_max_retries` and `default_sleep_retry_seconds` at the client level, which gets applied to all APIs by default.
2. Each API optionally has `max_retries` and `sleep_retry_seconds` parameters that, if specified, will override the default values from the client.

Fix and improve retry mechanism for Compass client

---

.github/workflows/autogenerate-release.yml

This Action should run each time `pyproject.toml` is updated on `main`
It will obtain the version number from `pyproject.toml`
It will check that version number to ensure isn't already a Tag
It will create the Tag and Release if it doesn't exist

ci: automatically create a release if pyproject.toml is updated and the version is not already tagged

---

cohere/compass/clients/parser.py
pyproject.toml

Allows supporting configurations where Parser authenticates using a Bearer token and not just user/password authentication.

feat: Add support for bearer tokens to CompassParserClient

---

cohere/compass/clients/compass.py

Retries are natural to happen and shouldn't log an error message but a warning, and only log an error if all retries failed, i.e. we couldn't make the request. This way we avoid unnecessary error logs if an API is temporarily unreliable.
In [SEA-1941](https://linear.app/cohereai/issue/SEA-1941/huge-volume-of-compass-related-logs) one of the complaints that North raised was related to retry logs which, along along with another issue, resulting in a huge volume of logs and frequent log rotation. The other issue (dumping asset base64 content in logs) was the major issue. However, to help them (and clients in general) in focusing on the important logs, we are making the retry logs warning, unless all retries fail in which cause we emit an error log. This way the logs dashboard for errors …

chore(send_request): change retry logs to warn

---

cohere/compass/clients/compass.py
cohere/compass/models/search.py
examples/compass_sdk_examples/scroll_all_chunks.py
pyproject.toml
tests/test_compass_client.py

Added methods `direct_search` and `direct_search_scroll`.
Added example for scrolling through all chunks in `scroll_all_chunks.py`.

feat: direct search and scroll all chunks

---

cohere/compass/clients/parser.py
examples/compass_sdk_examples/create_index.py
pyproject.toml

Update the `process_file` API to raise an exception in case there is an issue with parsing. The `process_files` API, which internally makes parallel calls to `process_file`, was then updated to capture exceptions raised by `process_file` and return them to the user so the user can track failed files.
This change also impacts the `process_folder` since it internally calls the `process_files` API.
This change is not backward compatible, and hence the minor version was bumped.

fix(parsing): [CMPS-28] Surface parsing errors

---

README.md

- RBAC code has been updated to use the new access_control module instead of the old rbac module.
- User, Group, and Role objects are now created using the new access_control models.
- The code for creating users, groups, and roles has been updated to use the new client methods.
- The code for adding users to groups, creating roles, and mapping roles to groups has been updated to use the new client methods.
- New code has been added for reading RBAC information, including listing users, groups, and roles, and getting detailed information about groups, users, and roles.
- The code for deleting RBAC entities has been updated to use the new client methods.
- Updated imports to use the new access_control module.
- Replaced UserCreateRequest, GroupCreateRequest, RoleCreateRequest, and …

chore: updating the README.md to show V2 RBAC usage instead of V1

---

cohere-compass-sdk.code-workspace
examples/.vscode/launch.json
examples/compass_sdk_examples/parse_document.py
examples/compass_sdk_examples/utils.py
examples/poetry.lock

The example calls the `process_file` of the parser SDK to parse a document.

feat: Add a new example for parsing documents

---

cohere_compass/clients/access_control.py
cohere_compass/clients/compass.py
cohere_compass/clients/rbac.py
examples/poetry.lock
pyproject.toml

This PR introduces a new parameter, `include_api_in_url`, to the `CompassRootClient` and `CompassClient` classes. This parameter allows users to specify whether the `/api` segment should be included in the base URL. The default value is set to `True` to maintain backward compatibility.
- **Added `include_api_in_url` Parameter**: A new optional parameter, `include_api_in_url`, has been added to the `__init__` methods of both `CompassRootClient` and `CompassClient`. This parameter controls whether the `/api` segment is included in the base URL.
- **Updated Base URL Construction**: The construction of the `base_url` has been updated to conditionally include `/api` based on the value of `include_api_in_url`.
- **Updated API Endpoints**: In `CompassClient`, the API endpoints have been updated …

fix: Remove required `/api` in url as not every deployment would have it

---

cohere_compass/clients/compass.py
cohere_compass/clients/compass_async.py
cohere_compass/clients/parser.py
cohere_compass/clients/parser_async.py
cohere_compass/models/config.py
examples/compass_sdk_examples/create_index.py

- Ingest files even if parsing had some errors; this is better than ignoring a file altogether.
- Fix URL generation for APIs.
- Add `enable_assets_returned_as_base64` flag to ParserConfig.
- For the `cerate_index` example, make the `folder_path` for files to be ingested optional (i.e. in case the user just wants to create an index without ingesting any data.)

chore: Multiple minor changes

---

cohere_compass/clients/compass.py
cohere_compass/models/search.py
tests/test_compass_client.py

This PR introduces the `SortBy` class and adds the `sort_by` parameter to the `direct_search` function.
- The `SortBy` class is added to the `cohere_compass.models.search` module. It has two fields: `field` and `order`.
- The `sort_by` parameter is added to the `direct_search` function in the `cohere_compass.clients.compass` module.
- The `DirectSearchInput` class is updated to include the `sort_by` field.
- The `data` variable in the `direct_search` function is updated to include the `sort_by` parameter.

feat: add sort to direct search

---

cohere_compass/models/documents.py
pyproject.toml

This PR introduces a new field, `asset_id`, to the `CompassDocumentChunkAsset` and `DocumentChunkAsset` classes.
- The `asset_id` field is added to the `CompassDocumentChunkAsset` class as an optional string with a default value of `None`.
- The `asset_id` field is added to the `DocumentChunkAsset` class as an optional string with a default value of `None`.

feat: Adding asset id to returned chunk

---

cohere_compass/clients/compass.py
pyproject.toml

This PR updates the `__init__` function in the `cohere_compass/clients/compass.py` file.
- `upload_documents`, `upload_documents_status`, and `download_parsed_document` are updated to remove the `_upload` from the `f-string` URL.

chore: Fix url for upload releases
