cohere-ai/cohere-compass-sdk

compass_sdk/compass.py
During testing we found this small path typo. Verified in e2e tests.
=> Fix broken path in RBAC edit authorization

compass_sdk/compass.py
This pull request removes a line of code from the `put_request` function in the `compass.py` file.
- The line `errors.append(doc)` has been removed.
=> fix: Remove docs logging 

compass_sdk/__init__.py, compass_sdk/compass.py, compass_sdk/parser.py, pyproject.toml
This pull request introduces changes to the `compass_sdk` module, specifically the `compass.py` and `__init__.py` files, to enhance document insertion and security features.
The PR adds new parameters, `authorized_groups` and `merge_groups_on_conflict`, to the `insert_doc`, `insert_docs_batch`, and `insert_docs` functions. These parameters enable fine-grained control over document insertion and security, allowing for more flexible and secure document handling.
- **New Parameters**: The `authorized_groups` and `merge_groups_on_conflict` parameters are introduced in the `insert_doc`, `insert_docs_batch`, and `insert_docs` functions.
- **Parameter Usage**: These new parameters are utilized in the `PutDocumentsInput` class to provide additional control over document insertion and security.
- …
=> Add group merging logic to update_doc calls 

pyproject.toml
Incrementing the version in the poetry definition for coordination with the main compass release. Will tag the release as well to bring these into alignment.
=> Increment version for tip of main

compass_sdk/__init__.py, compass_sdk/compass.py, pyproject.toml
This reverts commit 6c1c6dde31a83958c0e6d6fbd28a6a07ab487913.
=> Revert "Configurable heavy parsing strategy (#41)"

compass_sdk/compass.py
This pull request introduces changes to the `compass.py` file within the `compass_sdk` module. The modifications primarily focus on enhancing error handling and improving the clarity of error messages.
- **Removal of tqdm**: The `tqdm` library is no longer imported, and its usage has been removed from the `put_request` function. This change suggests a shift away from using `tqdm` for progress bar functionality.
- **Enhanced Error Messages**: The error handling logic in the `put_request` function has been updated. When appending errors to `doc.errors`, the error message now includes the filename, providing more context about the error's origin.
- **Modified Request Iteration**: The `requests_iter` variable in the `put_request` function has been modified. Instead of using `tqdm` to iterate …
=> Remove tqdm

.vscode/settings.json, compass_sdk/__init__.py, compass_sdk/compass.py, poetry.lock, pyproject.toml, tests/test_compass_client.py, tests/test_utils.py
Update the API endpoints in the SDK to match the recent changes to the API done in https://github.com/cohere-ai/compass/pull/567.
=> Update API endpoints

compass_sdk/compass.py
Created a method for accessing `search_chunks` Compass API.
=> Support search_chunk API

compass_sdk/__init__.py, compass_sdk/clients/compass.py, compass_sdk/models/datasources.py, pyproject.toml
Add support for:
- sync_datasource
- list_datasources_objects_states
=> Support more datasources APIs

cohere/compass/__init__.py, cohere/compass/clients/compass.py, cohere/compass/models/documents.py, cohere/compass/models/search.py, pyproject.toml, tests/test_compass_client.py
Addressed few other remaining renames related to [the recent API change](https://github.com/cohere-ai/compass/pull/594).
=> Renames related to the recent API renames

README.md
This pull request updates the import statements and modifies the search function in the `README.md` file. The changes involve using the `search_chunks` method instead of the `search` method, which likely enhances the search functionality by allowing for chunk-based searches.
- **Import Statements:** The import statements for the `CompassClient`, `CompassParserClient`, `MetadataStrategy`, and `MetadataConfig` have been updated to reflect the new module structure.
- **Search Function:** The `search` method has been replaced with the `search_chunks` method, which enables chunk-based searches and potentially improves the search process.
=> Updating readme with new sdk package structure

README.md
This PR introduces a new section titled "Adding filters to documents" in the README.md file, which provides two methods for adding filters to documents:
- **Adding filter via dict**: This method demonstrates how to add a filter using a dictionary. It imports the necessary modules, sets up the required variables, and creates a `CompassParserClient` instance. It then defines a custom context dictionary, processes the documents using the `process_folder` method, and creates a `CompassClient` instance. The code constructs a `SearchFilter` object, performs a search with the filter, and prints the results.
- **Adding filter via function**: This approach showcases adding a filter using a custom function. It imports the required modules, sets up the necessary variables, and creates a …
=> adding filters to readme

cohere/compass/clients/access_control.py, cohere/compass/models/access_control.py, pyproject.toml
New endpoints added in Compass, the SDK is being updated to match
Users now has a DetailedUser variant that contains the collection of Groups it belongs to
Also can now select Groups a User belongs to by the page.
=> Adding some User extensions to Access Control V2

.github/workflows/lint-pr.yaml
Used [action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request?tab=readme-ov-file#installation) for this, just like we did in [compass repo](https://github.com/cohere-ai/compass/pull/716/).
=> Add lint-pr GitHub workflow

cohere/compass/clients/access_control.py, cohere/compass/models/access_control.py, pyproject.toml
After testing the release we found some inconsistencies and broken objects. Fixing them up
=> fix: access_control testing fixes/clean up

README.md
This pull request adds a new section to the README.md file, providing installation instructions for the Cohere Compass SDK. The changes include:
- A new section titled "Installation" is added to the README.md file.
- The installation command using `pip` is provided to install the SDK from GitHub.
- The necessary Python imports from the SDK are included.
=> docs: Adding installation section

examples/compass_sdk_examples/create_index.py, examples/compass_sdk_examples/list_indexes.py, examples/compass_sdk_examples/search_documents.py, examples/pyproject.toml
This pull request introduces several changes to the Compass SDK examples, enhancing the functionality and user experience.
- The `parse_args()` function is added to parse the `index_name` and `folder_path` using `argparse`.
- The `main()` function now calls `parse_args()` to get the `index_name` and `folder_path` arguments.
- The `index_name` and `folder_path` are used when creating the index and inserting documents.
- The `folder_path` is now a user-provided argument, allowing for flexibility in document insertion.
- The `print("Printing response...")` line is removed.
- The `assert response.error is None` line is added to check for errors in the response.
- The `assert response.result is not None` line is added to ensure the response has a result.
- The `indexes = …
=> chore: Parameterize the examples to improve usability

cohere/compass/clients/compass.py, cohere/compass/models/search.py, examples/compass_sdk_examples/get_document_asset.py, examples/compass_sdk_examples/list_indexes.py, pyproject.toml, tests/test_compass_client.py
Add a method for the get_document_asset API introduced in https://github.com/cohere-ai/compass/pull/825.
=> feat: Add a method for get_document_asset API

examples/poetry.lock, pyproject.toml
The PR updates the version of the Compass SDK in the examples/poetry.lock and pyproject.toml files.
- The version of the Compass SDK in the examples/poetry.lock file has been updated from 0.21.0 to 1.0.0.
- The version of the Compass SDK in the pyproject.toml file has been updated from 0.21.0 to 1.0.0.
=> chore: Bump the major version of the package

cohere_compass/models/config.py
Small change to allow setting the analyzer when creating the index. especially useful for icu and nori
=> feat(main): Allow setting the analyzer when creating the index

cohere_compass/clients/compass.py, cohere_compass/clients/parser.py, pyproject.toml
Make the `CompassClient` and `CompassParserClient` thread safe.
=> feat: Make the clients thread safe

.github/workflows/test.yml, cohere_compass/__init__.py, poetry.lock, pyproject.toml
Adding github action to publish package to pypi. Also renaming the project name to be consistent with github project 
https://pypi.org/project/cohere-compass-sdk/
=> ci: Adding publish.yaml

.github/workflows/autogenerate-release.yml, .github/workflows/test.yml, pyproject.toml
Bumping version of adding model validator to Compass documents and chunk content
Fixing publish script path
=> fix: publish script path

cohere_compass/models/documents.py
Removing validation: `document.content` should contains all fields specified in `index_fields`. 
Since compass version >=[0.19.0](https://github.com/cohere-ai/compass/compare/v0.18.0...v0.19.0) released in chart >=2.21.2 `document.content` is not extracted and thus this validation is not required
=> fix: Removing validation for document.content

pyproject.toml
The pyproject.toml file has been updated to reflect a new version of the cohere-compass-sdk package.
- The version has been updated from 1.6.0 to 1.7.0.
=> chore: release compass-sdk 1.7.0
